# Label Instruction
# Instruksi label merupakan instruksi yang digunakan untuk menambahkan metadata ke dalam docker image yang kita buat
# Metadata adalah informasi tambahan misal seperti nama aplikasi, pembuat, website, perusahaan, lisensi dll
# metadaata hanya berguna sebagai informasi saja, tidaka akan dungakan ketika kita menjalakan docker container